version: '3.8'

services:
  # 1. Frontend (Weboldal)
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # 2. Backend (API) - ITT VOLT A HIBA, MOST JAVÍTVA
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Ez a sor utasítja a Dockert, hogy olvassa be a titkos .env fájlt
    env_file:
      - .env
    depends_on:
      - db

  # 3. Adatbázis (Helyi verzió)
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: